/**
 * Legacy barrel file for backward compatibility.
 * All logic moved to src/lib/repositories/ (split by controller/domain).
 * Import from @/lib/repositories for new code.
 */

// Re-export types
export type {
    OrderStatus,
    Product,
    StockLevel,
    Design,
    OrderItem,
    Order,
    OrderWithItems,
    AuditLog,
    ContactSubmission,
    NewsletterSubscription,
    StaticContent,
    Review,
    Investment,
} from "@/lib/repositories";

// Re-export all repository functions
export {
    getProductById,
    getProductBySlug,
    getAllProducts,
    getActiveProducts,
    getFeaturedProducts,
    createProduct,
    updateProduct,
    deleteProduct,
    getStockLevelsByProductId,
    getAllStockLevels,
    getStockTotalsByProduct,
    createStockLevel,
    updateStockLevel,
    getLowStockAlerts,
    deleteStockLevelsByProductId,
    getOrderById,
    getAllOrders,
    getRecentOrders,
    getOrdersWithItems,
    getRecentOrdersWithItems,
    createOrder,
    updateOrder,
    countOrders,
    aggregateOrderTotal,
    getOrderItemsByOrderId,
    createOrderItem,
    getDesignById,
    createDesign,
    createAuditLog,
    createContactSubmission,
    getContactSubmissions,
    createNewsletterSubscription,
    getNewsletterSubscriptions,
    getStaticContentByKey,
    getAllStaticContent,
    upsertStaticContent,
    deleteStaticContent,
    getAllReviews,
    getActiveReviews,
    createReview,
    updateReview,
    deleteReview,
    getAllInvestments,
    createInvestment,
    updateInvestment,
    deleteInvestment,
    getTotalInvestment,
} from "@/lib/repositories";
